### ISSUE TITLE
Error with lite classifier en-fr

### ISSUE THREAD

**Issue by jgcb00** [bitextor/bicleaner-ai#10]
Hi,
The installation went well,
I used the big model without any issue but I got an error when I'm trying to use the light model

my command : 
```
 bicleaner-ai-classify --scol 1 --tcol 2 --disable_minimal_length --disable_hardrules --disable_lm_filter --disable_porn_removal file1 file1.med en-fr/metadata.yaml
```

the error : 
```
022-03-10 13:02:56,128 - INFO - Loaded SentencePiece model
2022-03-10 13:02:56,128 - INFO - Loading neural classifier
/opt/pyenv3/lib/python3.6/site-packages/keras/layers/core.py:1045: UserWarning: decomposable_attention is not loaded, but a Lambda layer uses it. It may cause errors.
  , UserWarning)
2022-03-10 13:02:56,371 - ERROR - Error loading metadata
Traceback (most recent call last):
  File "/opt/pyenv3/lib/python3.6/site-packages/bicleaner_ai/classify.py", line 93, in load_metadata
    args.clf.load()
  File "/opt/pyenv3/lib/python3.6/site-packages/bicleaner_ai/models.py", line 263, in load
    custom_objects=deps, compile=False)
  File "/opt/pyenv3/lib/python3.6/site-packages/keras/saving/save.py", line 201, in load_model
    compile)
  File "/opt/pyenv3/lib/python3.6/site-packages/keras/saving/hdf5_format.py", line 181, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/opt/pyenv3/lib/python3.6/site-packages/keras/saving/model_config.py", line 52, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/opt/pyenv3/lib/python3.6/site-packages/keras/layers/serialization.py", line 212, in deserialize
    printable_module_name='layer')
  File "/opt/pyenv3/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 678, in deserialize_keras_object
    list(custom_objects.items())))
  File "/opt/pyenv3/lib/python3.6/site-packages/keras/engine/functional.py", line 663, in from_config
    config, custom_objects)
  File "/opt/pyenv3/lib/python3.6/site-packages/keras/engine/functional.py", line 1273, in reconstruct_from_config
    process_layer(layer_data)
  File "/opt/pyenv3/lib/python3.6/site-packages/keras/engine/functional.py", line 1255, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/opt/pyenv3/lib/python3.6/site-packages/keras/layers/serialization.py", line 212, in deserialize
    printable_module_name='layer')
  File "/opt/pyenv3/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 678, in deserialize_keras_object
    list(custom_objects.items())))
  File "/opt/pyenv3/lib/python3.6/site-packages/keras/layers/core.py", line 1006, in from_config
    config, custom_objects, 'function', 'module', 'function_type')
  File "/opt/pyenv3/lib/python3.6/site-packages/keras/layers/core.py", line 1058, in _parse_function_from_config
    config[func_attr_name], globs=globs)
  File "/opt/pyenv3/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 789, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)
```

If it can helps : 
```
tensorflow              2.6.2
```
How can I solve this ?
Thanks,

**Comment by jgcb00** [comment]
Okay thanks.
Just another question, is inference on GPU possible ? It doesn't seem to but it will be create !

**Comment by ZJaume** [comment]
Yes, of course. If it does not work you probably have wrong TF version for your CUDA version or missing some libraries. Enable [TF logging](https://github.com/bitextor/bicleaner-ai#tensorflow) and see if everything is ok.

**Comment by jgcb00** [comment]
Okay, thanks is it possible to specify the gpu you want to use ?

**Comment by ZJaume** [comment]
You only need to set `CUDA_VISIBLE_DEVICES`.

**Comment by jgcb00** [comment]
Okay nice ! Thanks.
Does the performance parallelize well on GPU or it's better to launch several distinct process ?

**Comment by ZJaume** [comment]
There is no support for multi-gpu, you should run one bicleaner process for each gpu with gnu parallel for example.

**Comment by jgcb00** [comment]
Hi, it appears to also not be compatible with python3.10 as glove-python-binary==0.2.0 isn't available on python3.10

Do you have a quick fix, I tried to build it from source but :
```
git clone https://github.com/maciejkula/glove-python.git
cd glove-python
python3.10 setup.py build
```
exit with an error : 
```
glove/glove_cython.c: In function ‘__Pyx_ExceptionSave’:
glove/glove_cython.c:16753:21: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
     *type = tstate->exc_type;
                     ^~~~~~~~
                     curexc_type
glove/glove_cython.c:16754:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
     *value = tstate->exc_value;
```
I know it's not your package but it semms to not be maintain anymore...

**Comment by ZJaume** [comment]
I've updated the `gensim` branch to master. It has the glove dependency replaced by Gensim vectors.

**Comment by jgcb00** [comment]
thanks

**Comment by jgcb00** [comment]
I still get an issue while building from source :
```
python3.10 -m venv bicleaner_ai_env
ssource /home/j-g.barthelemy/bicleaner_ai_env/bin/activate
git clone https://github.com/kpu/kenlm
cd kenlm
pip install . --install-option="--max_order 7"
mkdir -p build && cd build
cmake .. -DKENLM_MAX_ORDER=7 -DCMAKE_INSTALL_PREFIX:PATH=/myhome
make -j all install
cd ../..
git clone https://github.com/bitextor/bicleaner-ai.git
git checkout gensim
python setup.py build
python setup.py install
```
The last command give me :
```
ownloading https://files.pythonhosted.org/packages/4b/6d/22a9a2b934344fbf25ab2613543eeeb724ffd3ba7376e8fed88aabe885c8/gensim-4.1.2.tar.gz#sha256=1932c257de4eccbb64cc40d46e8577a25f5f47b94b96019a969fb36150f11d15
Best match: gensim 4.1.2
Processing gensim-4.1.2.tar.gz
Writing /tmp/easy_install-h1tt7l8b/gensim-4.1.2/setup.cfg
Running gensim-4.1.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-h1tt7l8b/gensim-4.1.2/egg-dist-tmp-8h4w1fs7
Traceback (most recent call last):
  File "/home/j-g.barthelemy/bicleaner_ai_env/lib/python3.10/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/home/j-g.barthelemy/bicleaner_ai_env/lib/python3.10/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/j-g.barthelemy/bicleaner_ai_env/lib/python3.10/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/home/j-g.barthelemy/bicleaner_ai_env/lib/python3.10/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-h1tt7l8b/gensim-4.1.2/setup.py", line 339, in <module>
  File "/home/j-g.barthelemy/bicleaner_ai_env/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/j-g.barthelemy/bicleaner_ai_env/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 155, in run
    self.run_command("egg_info")
  File "/usr/local/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/j-g.barthelemy/bicleaner_ai_env/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 299, in run
    self.find_sources()
  File "/home/j-g.barthelemy/bicleaner_ai_env/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 306, in find_sources
    mm.run()
  File "/home/j-g.barthelemy/bicleaner_ai_env/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 541, in run
    self.add_defaults()
  File "/home/j-g.barthelemy/bicleaner_ai_env/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 578, in add_defaults
    sdist.add_defaults(self)
  File "/usr/local/lib/python3.10/distutils/command/sdist.py", line 228, in add_defaults
    self._add_defaults_ext()
  File "/usr/local/lib/python3.10/distutils/command/sdist.py", line 311, in _add_defaults_ext
    build_ext = self.get_finalized_command('build_ext')
  File "/usr/local/lib/python3.10/distutils/cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/local/lib/python3.10/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/tmp/easy_install-h1tt7l8b/gensim-4.1.2/setup.py", line 109, in finalize_options
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
```

**Comment by jgcb00** [comment]
Successfully installed bicleaner-ai :

```
python3.10 -m venv bicleaner_ai_env
source bicleaner_ai_env/bin/activate

git clone https://github.com/kpu/kenlm
cd kenlm
python3 -m pip install . --install-option="--max_order 7"
mkdir -p build && cd build
cmake .. -DKENLM_MAX_ORDER=7 -DCMAKE_INSTALL_PREFIX:PATH=/myprefix/path
make -j all install

cd ..
cd ..

curl https://sh.rustup.rs -sSf | sh -s -- -y
export PATH="$HOME/.cargo/bin:$PATH"
pip install setuptools_rust

python3 -m pip install tokenizers==0.10.3
python3 -m pip install scikit-learn>=0.22.1
python3 -m pip install PyYAML>=5.1.2
python3 -m pip install numpy
python3 -m pip install pytest
python3 -m pip install toolwrapper
python3 -m pip install joblib
python3 -m pip install sacremoses
python3 -m pip install bicleaner-hardrules>=2.0
python3 -m pip install sentencepiece
python3 -m pip install tensorflow
python3 -m pip install fuzzywuzzy
python3 -m pip install python-Levenshtein
python3 -m pip install transformers==4.10.3
python3 -m pip install psutil
python3 -m pip install gensim>=4

git clone https://github.com/bitextor/bicleaner-ai.git
cd bicleaner-ai
git checkout gensim
python setup.py build
python setup.py install
```
