### ISSUE TITLE
xlmr XLMRobertaTokenizerFast load spm failed

### ISSUE THREAD

**Issue by mathxin** [bitextor/bicleaner-ai#15]
sentencepiece cannot load **jplu/tf-xlm-roberta-base/sentencepiece.bpe.model** 

`Traceback (most recent call last):
  File "/home/pcl_user/anaconda3/envs/fairseq/bin/bicleaner-ai-train", line 11, in <module>
    main(sys.argv[1:])
  File "/home/pcl_user/anaconda3/envs/fairseq/bin/bicleaner-ai-train", line 8, in main
    train.main(args)
  File "/home/pcl_user/anaconda3/envs/fairseq/lib/python3.7/site-packages/bicleaner_ai/bicleaner_ai_train.py", line 232, in main
    perform_training(args)
  File "/home/pcl_user/anaconda3/envs/fairseq/lib/python3.7/site-packages/bicleaner_ai/bicleaner_ai_train.py", line 213, in perform_training
    y_true, y_pred = classifier.train(train_sentences, dev_sentences)
  File "/home/pcl_user/anaconda3/envs/fairseq/lib/python3.7/site-packages/bicleaner_ai/models.py", line 551, in train
    self.settings["model"])
  File "/home/pcl_user/anaconda3/envs/fairseq/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1705, in from_pretrained
    resolved_vocab_files, pretrained_model_name_or_path, init_configuration, *init_inputs, **kwargs
  File "/home/pcl_user/anaconda3/envs/fairseq/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1722, in _from_pretrained
    **(copy.deepcopy(kwargs)),
  File "/home/pcl_user/anaconda3/envs/fairseq/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1776, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/pcl_user/anaconda3/envs/fairseq/lib/python3.7/site-packages/transformers/models/xlm_roberta/tokenization_xlm_roberta.py", line 135, in __init__
    self.sp_model.Load(str(vocab_file))
  File "/home/pcl_user/anaconda3/envs/fairseq/lib/python3.7/site-packages/sentencepiece/__init__.py", line 367, in Load
    return self.LoadFromFile(model_file)
  File "/home/pcl_user/anaconda3/envs/fairseq/lib/python3.7/site-packages/sentencepiece/__init__.py", line 171, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: /sentencepiece/python/bundled/sentencepiece/src/sentencepiece_processor.cc(823) [model_proto->ParseFromArray(serialized.data(), serialized.size())] `

**Comment by ZJaume** [comment]
Could you please post your Python and packages (Bicleaner AI, Transformers, TensorFlow) versions?

**Comment by ZJaume** [comment]
Closing, if there are news on this, feel free to reopen it.
