### ISSUE TITLE
Bad file descriptor after training

### ISSUE THREAD

**Issue by ZJaume** [bitextor/bicleaner-ai#19]
```python
Exception ignored in: <function Pool.__del__ at 0x7fe1e3f8edc0>
Traceback (most recent call last):
  File "/home/jzaragoza/miniconda3/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
    self._change_notifier.put(None)
  File "/home/jzaragoza/miniconda3/lib/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/home/jzaragoza/miniconda3/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/jzaragoza/miniconda3/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/home/jzaragoza/miniconda3/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
```

Known [bug](https://github.com/tensorflow/tensorflow/issues/50487) in TensorFlow when using MirroredStrategy. It doesn't affect the results of the training.

**Comment by suchunxie** [comment]
hi @ZJaume , do you know how to solve this ? I checked the answer in other post, but dont know wehere the code should be added to .

**Comment by ZJaume** [comment]
There's no solution until they fix the bug. The workaround is to stop using multi-gpu and use single gpu, changing
```
strategy = tf.distribute.MirroredStrategy()
```
with
```
strategy = tf.distribute.OneDeviceStrategy()
```
would do the trick, as far as you don't need more than one gpu.
