### ISSUE TITLE
`--rules_config` option doesn't work

### ISSUE THREAD

**Issue by jelmervdl** [bitextor/bicleaner-ai#26]
When I try to use it, I get this error:
```
Traceback (most recent call last):
  File "/home/cs-vand1/src/bitextor/env-gpu/bin/bicleaner-ai-classify", line 8, in <module>
    sys.exit(main())
  File "/home/cs-vand1/src/bitextor/env-gpu/lib/python3.8/site-packages/bicleaner_ai/bicleaner_ai_classifier.py", line 117, in main
    perform_classification(args) # Main loop
  File "/home/cs-vand1/src/bitextor/env-gpu/lib/python3.8/site-packages/bicleaner_ai/bicleaner_ai_classifier.py", line 106, in perform_classification
    nline = classify(args, args.input, args.output)
  File "/home/cs-vand1/src/bitextor/env-gpu/lib/python3.8/site-packages/bicleaner_ai/classify.py", line 192, in classify
    hardrules = Hardrules(args)
  File "/home/cs-vand1/src/bitextor/env-gpu/lib/python3.8/site-packages/hardrules/hardrules.py", line 130, in __init__
    dif = args.rules_config.keys() - self.rule_pipeline.keys()
AttributeError: '_io.TextIOWrapper' object has no attribute 'keys'
```

**Comment by mbanon** [comment]
Can I get the full command that is giving the error, plz? @jelmervdl

**Comment by jelmervdl** [comment]
```
$ bicleaner-ai-classify --rules_config ./bicleaner-rules.yaml /dev/stdin / model/metadata.yaml
2023-06-07 21:41:13,490 - WARNING - Porn removal not present in metadata, disabling
2023-06-07 21:41:13,491 - INFO - Arguments processed
2023-06-07 21:41:13,491 - INFO - Starting process
Traceback (most recent call last):
  File "/home/cs-vand1/src/bitextor/env-gpu/bin/bicleaner-ai-classify", line 8, in <module>
    sys.exit(main())
  File "/home/cs-vand1/src/bitextor/env-gpu/lib/python3.8/site-packages/bicleaner_ai/bicleaner_ai_classifier.py", line 117, in main
    perform_classification(args) # Main loop
  File "/home/cs-vand1/src/bitextor/env-gpu/lib/python3.8/site-packages/bicleaner_ai/bicleaner_ai_classifier.py", line 106, in perform_classification
    nline = classify(args, args.input, args.output)
  File "/home/cs-vand1/src/bitextor/env-gpu/lib/python3.8/site-packages/bicleaner_ai/classify.py", line 192, in classify
    hardrules = Hardrules(args)
  File "/home/cs-vand1/src/bitextor/env-gpu/lib/python3.8/site-packages/hardrules/hardrules.py", line 130, in __init__
    dif = args.rules_config.keys() - self.rule_pipeline.keys()
AttributeError: '_io.TextIOWrapper' object has no attribute 'keys'
```

- bicleaner-ai-classify 2.2.1
- bicleaner-hardrules 2.8.1

<details>
  <summary>bicleaner-rules.yaml</summary>

```yaml
no_empty: True
not_too_long: 1024
not_too_short: 3
length_ratio: False
no_identical: True
no_literals: ["Re:","{{", "%s", "}}", "+++", "***", '=\"']
no_only_symbols: True
no_only_numbers: True
no_urls: False
no_breadcrumbs: True
no_glued_words: True
no_repeated_words: False
no_unicode_noise: True
no_space_noise: True
no_paren: True
no_escaped_unicode: True
no_bad_encoding: True
no_titles: False
no_number_inconsistencies: False
no_script_inconsistencies: False
no_wrong_language: 1
no_porn: True
lm_filter: True
```

</details>

I could work around it by adding a `args.rules_config = yaml.safe_load(args.rules_config)` somewhere. In the end I chose to split the hardrules and bicleaner-ai step into two separate jobs.

**Comment by mbanon** [comment]
It's fixed now in v.2.2.2
