### ISSUE TITLE
Issues with dependencies for Python 3.10/11

### ISSUE THREAD

**Issue by eu9ene** [bitextor/bicleaner-ai#31]
I'm trying to lock dependencies for `bicleaner-ai==3.0.1` and Python 3.10.14 on Linux and getting an issue:
```
$ cat reqs.in
bicleaner-ai==3.0.1

$pip-compile reqs.in
  ERROR: Cannot install bicleaner-hardrules because these package versions have conflicting dependencies.
Discarding cyhunspell==2.0.2 (from -r reqs.txt (line 29)) to proceed the resolution
  ERROR: Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10
  ERROR: Could not find a version that satisfies the requirement cyhunspell<=2.0.3,>=2.0.2 (from fastspell) (from versions: 1.0.1, 1.1.0, 1.1.3, 1.1.3.post1, 1.1.4, 1.2.0, 1.2.1, 1.3.0, 1.3.2, 1.3.3, 1.3.4)
Traceback (most recent call last):
  File "/data/rw/evgeny/mambaforge/envs/piplock_python310/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 316, in _backjump
    name, candidate = broken_state.mapping.popitem()
KeyError: 'dictionary is empty'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/rw/evgeny/mambaforge/envs/piplock_python310/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "/data/rw/evgeny/mambaforge/envs/piplock_python310/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/data/rw/evgeny/mambaforge/envs/piplock_python310/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 434, in resolve
    success = self._backjump(causes)
  File "/data/rw/evgeny/mambaforge/envs/piplock_python310/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 318, in _backjump
    raise ResolutionImpossible(causes)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('cyhunspell<=2.0.3,>=2.0.2'), parent=LinkCandidate('https://files.pythonhosted.org/packages/95/23/e837768b8bd548e1b3b607198fd8d179ffe2f9d68ad867192185cf1ae7b4/fastspell-0.11-py3-none-any.whl (from https://pypi.org/simple/fastspell/) (requires-python:>=3.8)'))]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/rw/evgeny/mambaforge/envs/piplock_python310/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/data/rw/evgeny/mambaforge/envs/piplock_python310/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/data/rw/evgeny/mambaforge/envs/piplock_python310/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/data/rw/evgeny/mambaforge/envs/piplock_python310/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/rw/evgeny/mambaforge/envs/piplock_python310/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/data/rw/evgeny/mambaforge/envs/piplock_python310/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/data/rw/evgeny/mambaforge/envs/piplock_python310/lib/python3.10/site-packages/piptools/scripts/compile.py", line 470, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/data/rw/evgeny/mambaforge/envs/piplock_python310/lib/python3.10/site-packages/piptools/resolver.py", line 604, in resolve
    is_resolved = self._do_resolve(
  File "/data/rw/evgeny/mambaforge/envs/piplock_python310/lib/python3.10/site-packages/piptools/resolver.py", line 636, in _do_resolve
    resolver.resolve(
  File "/data/rw/evgeny/mambaforge/envs/piplock_python310/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 104, in resolve
    raise error from e
pip._internal.exceptions.DistributionNotFound: No matching distribution found for cyhunspell<=2.0.3,>=2.0.2
```

I see the same issue for Python 3.11.
It works for Python 3.9

I'm using `pip-compile` tool which requires `pip install pip-tools`.

**Comment by eu9ene** [comment]
Ok, I found that it now requires adding explicitly `[cython_hunspell](git+https://github.com/MSeal/cython_hunspell@2.0.3)`. It works when I add it to the requirements. Closing then.

**Comment by ZJaume** [comment]
Hi @eu9ene, you might be interested in the new [multilingual models](https://github.com/bitextor/bicleaner-ai?tab=readme-ov-file#multilingual-models). Our first experiments show that they might perform equal or better than bilingual models.

**Comment by eu9ene** [comment]
Great news! I'm integrating them [here](https://github.com/mozilla/firefox-translations-training/pull/604). We're going to train a bunch of [languages](https://github.com/mozilla/firefox-translations-training/issues/524) soon and those models will be useful for at least 5 of them. I'm going to use the `full-large` models. Would you recommend switching to those for all the languages, even for those with specialized models available?

**Comment by ZJaume** [comment]
Yes, I would recommend that.
