### ISSUE TITLE
en-fr lite model does not work

### ISSUE THREAD

**Issue by cgr71ii** [bitextor/bicleaner-ai#9]
I have run Bicleaner-AI with the available [en-fr lite model](https://github.com/bitextor/bicleaner-ai-data/releases/download/v1.0/lite-en-fr.tgz), but it does not work.

The command I run is:
```bash
cat /home/cgarcia/tmp/bitextor-test-821/transient-mto3-en-fr/en_fr/07_01.bifixer/0 \
  | tail -n 1 \
  | bicleaner-ai-classify --score_only -q - - /home/cgarcia/tmp/bitextor-test-821/bicleaner-ai-model/en-fr/metadata.yaml
```

The input:
```
https://greenwire.greenpeace.org/canada/en/search/event/%20/search_api_relevance%20DESC/thumbnail/100?page=1  https://greenwire.greenpeace.org/canada/fr/search/event/%20/participants%20DESC/thumbnail/50?page=4   Greenpeace.org/canada   Greenpeace.org/canada   1.000000    e6959a14adbd56b9        96.57
```

The error:
```
/home/cgarcia/miniconda3/envs/bitextor/lib/python3.8/site-packages/keras/layers/core/lambda_layer.py:303: UserWarning: decomposable_attention is not loaded, but a Lambda layer uses it. It may cause errors.
  function = cls._parse_function_from_config(config, custom_objects,
2022-03-09 11:42:49,405 - ERROR - Error loading metadata
Traceback (most recent call last):
  File "/home/cgarcia/miniconda3/envs/bitextor/lib/python3.8/site-packages/bicleaner_ai/classify.py", line 97, in load_metadata
    args.clf.load()
  File "/home/cgarcia/miniconda3/envs/bitextor/lib/python3.8/site-packages/bicleaner_ai/models.py", line 267, in load
    self.model = load_model(self.dir+'/'+self.settings["model_file"],
  File "/home/cgarcia/miniconda3/envs/bitextor/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/lustre/home/dc007/jzaragoz/bcneural-trainings/bicleaner-neural/bicleaner/decomposable_attention.py", line 152, in _normalize
    # Make use of existing autocomputation but provide Lambda-specific
NameError: Exception encountered when calling layer "lambda_1" (type Lambda).

name 'K' is not defined

Call arguments received:
  • inputs=tf.Tensor(shape=(None, 100, 100), dtype=float32)
  • mask=None
  • training=False
```

BTW 1: binary `bicleaner-ai-classify-lite` does not exist, so I assume that the binary which I have to use is `bicleaner-ai-classify`.
BTW 2: it seems that there is a hard-coded path somewhere:
```
/lustre/home/dc007/jzaragoz/bcneural-trainings/bicleaner-neural
```

**Comment by ZJaume** [comment]
Latest change should be fixing it

**Comment by cgr71ii** [comment]
Now it works! Thank you!

**Comment by ZJaume** [comment]
*-lite script was the bicleaner version without python multiprocessing parallelization to compute classifier features. Since we are using neural networks, that does not have any sense now.
